// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiy23qIxaeKfrerTkC78uxTj4AS2mmu48',
    appId: '1:700325275973:web:063b6e4240c608519e362c',
    messagingSenderId: '700325275973',
    projectId: 'imk-kel-1',
    authDomain: 'imk-kel-1.firebaseapp.com',
    storageBucket: 'imk-kel-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRWAOlP0bZRhJ4dwO9ahp7ZIMq7x8IP-A',
    appId: '1:700325275973:android:b8981f3b76adf3cc9e362c',
    messagingSenderId: '700325275973',
    projectId: 'imk-kel-1',
    storageBucket: 'imk-kel-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgM3Xqw0gClmYbukNna880_9ius9qYfu4',
    appId: '1:700325275973:ios:7fb64f35ba1dbae59e362c',
    messagingSenderId: '700325275973',
    projectId: 'imk-kel-1',
    storageBucket: 'imk-kel-1.appspot.com',
    iosClientId: '700325275973-uc0npmiamtg5aak9vobtfrkb5othti6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tunaRunguApps',
  );
}
